[test_browser_cell_data.py]
carrier = true
# Bug 850313 Cannot browse via the cellular network after manual flash Unagi
xfail = true
[test_browser_lan.py]
lan = true
